version: '3.7'

services:

  uffs-calendar-php:
    container_name: uffs-calendar-php
    build:
      context: .
      dockerfile: php.dockerfile
    working_dir: /var/www
    links:
      - uffs-calendar-database
    volumes:
      - ./backend/:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=uffs-calendar-database"
      - "DB_PASSWORD=secret"


  uffs-calendar-web:
    container_name: uffs-calendar-web
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - 8080:80

  uffs-calendar-database:
    container_name: uffs-calendar-database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

  uffs-calendar-node:
    container_name: uffs-calendar-node
    environment:
      env_file: .env
      NODE_ENV: development
    build:
      context: .
      dockerfile: "node.dockerfile"
    ports:
      - "3000"
    restart: always

volumes:
  dbdata:
