version: '3.7'

services:

  uffs-calendar-php:
    container_name: uffs-calendar-php
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        UID: ${U_ID}
        GID: ${G_ID}
    links:
      - uffs-calendar-database
    volumes:
      - ./backend/:/var/www/html
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=uffs-calendar-database"
      - "DB_DATABASE=uffscalendar"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"

  uffs-calendar-web:
    container_name: uffs-calendar-web
    depends_on:
      - uffs-calendar-php
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8080:80

  uffs-calendar-database:
    container_name: uffs-calendar-database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=uffscalendar"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
        - "33061:3306"

  uffs-calendar-node:
    container_name: uffs-calendar-node
    volumes:
      - ./frontend:/usr/src/app
    command: npm start
    environment:
      env_file: .env
      NODE_ENV: development
    build:
      context: .
      dockerfile: "node.dockerfile"
    ports:
      - "3000:3000"
    restart: always

volumes:
  dbdata:
