version: '3.7'

services:

  ucalendar-php:
    container_name: ucalendar-php
    build:
      context: .
      dockerfile: docker/php.dockerfile
      args:
        UID: ${U_ID}
        GID: ${G_ID}
    links:
      - ucalendar-database
    volumes:
      - ./backend/:/var/www/html
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=ucalendar-database"
      - "DB_DATABASE=ucalendar"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"

  ucalendar-web:
    container_name: ucalendar-web
    depends_on:
      - ucalendar-php
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8080:80

  ucalendar-database:
    container_name: ucalendar-database
    image: mysql:5.7
    volumes:
      - ucalendar-dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=ucalendar"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
        - "33061:3306"

  ucalendar-node:
    container_name: ucalendar-node
    volumes:
      - ./frontend:/usr/src/app
    command: npm start
    environment:
      env_file: .env
      NODE_ENV: development
    build:
      context: .
      dockerfile: docker/node.dockerfile
    ports:
      - "3000:3000"
    restart: always

volumes:
  ucalendar-dbdata:
